openapi: "3.0.0"
info:
  version: 1.0.0
  title: ¡ApiCustomer!
servers:
  - url: http://localhost:8080
paths:
  /customers:
    get:
      summary: Registro cuentas
      operationId: cuentas
      tags:
        - accounts
      responses:
        '200':
          description: Consulta de cuentas
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountsResponse"
components:
  schemas:
    AccountRequest:
      type: object
      properties:
        id:
          type: Long
          description: ID único de cuenta
        type:
          accountNumber: String
          description: Número de la cuenta
        balance:
          type: Double
          description: saldo en la cuenta
        accountType:
          type: AccountType
          description: Tipo de cuenta
        customerId:
          type: Long
          description: ID de cliente

    CustomerResponse:
      type: object
      properties:
        id:
          type: Long
          description: ID único de cuenta
        type:
          accountNumber: String
          description: Número de la cuenta
        balance:
          type: Double
          description: saldo en la cuenta
        accountType:
          type: AccountType
          description: Tipo de cuenta
        customerId:
          type: Long
          description: ID de cliente